import '../styles/globals.css'
import Head from 'next/head'
import { ChakraProvider , extendTheme } from "@chakra-ui/react"

const colors = {
  brand: {
    400: "#defffc",
    500: "#e2e4f6",
    600: "#e7c8dd",
    700: "#dbafc1",
    800: "#c98ecd",
    900: "#86626e",
  },
}
const theme = extendTheme({ colors })

function MyApp({ Component, pageProps }) {
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>Hand Pong</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps}/>
    </ChakraProvider>
  )
}

export default MyApp
